import {
  redFlat,
  tgIcon,
  vkIcon,
  waIcon,
  bisnesCar,
  busCar,
  comfortCar,
  minivenCar,
  vClassCar,
  watherFallsImg1,
  watherFallsImg2,
  watherFallsImg3,
  blueLaceImg,
  divingImg,
  gaagrImg,
} from '../assets';

export const socialLinks = [
  {
    name: 'vk',
    link: 'https://vk.com/familytour_sochi',
    description: 'Ссылка на нашу группу в ВК',
    src: vkIcon,
  },
  {
    name: 'tg',
    link: 'https://t.me/+9PR0IhZB_R44OTUy',
    description: 'Ссылка на наш телеграмм канал',
    src: tgIcon,
  },
  {
    name: 'wa',
    link: '#',
    description: 'Ссылка для связи WhatsApp',
    src: waIcon,
  },
];

export const menuLinks = [
  {
    name: 'Экскурсии',
    link: '#excurs',
  },
  {
    name: 'VIP-Туры',
    link: '#vipTours',
  },
  {
    name: 'Море',
    link: '#sea',
  },
  {
    name: 'Отели',
    link: '#hotels',
  },
  {
    name: 'Трансфер',
    link: '#transfers',
  },
  {
    name: 'Отзывы',
    link: '#reviwes',
  },
  {
    name: 'Контакты',
    link: '#contacts',
  },
];

export const excursCardsInfo = [
  {
    id: 0,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: true,
    isNew: true,
    startPrice: '500р',
  },
  {
    id: 2,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: true,
    startPrice: '500р',
  },
  {
    id: 3,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: true,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 4,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 5,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 6,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 7,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 8,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
];

export const vipToursCardsInfo = [
  {
    id: 0,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: true,
    isNew: true,
    startPrice: '500р',
  },
  {
    id: 2,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: true,
    startPrice: '500р',
  },
  {
    id: 3,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: true,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 4,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 5,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 6,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 7,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
  {
    id: 8,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '500р',
  },
];

export const seaCardsInfo = [
  {
    id: 0,
    name: 'Морские прогулки',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 1,
    name: 'Рыбалка',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 2,
    name: 'Дайвинг',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 3,
    name: 'Аренда яхт и катеров',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
];

export const hotelsCardsInfo = [
  {
    id: 0,
    name: 'Сочи',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 1,
    name: 'Красная поляна',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 2,
    name: 'Абхазия',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 3,
    name: 'Геленжик',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 4,
    name: 'Анапа',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
  {
    id: 5,
    name: 'Крым',
    order: '',
    description: '',
    img: [redFlat],
    isHit: false,
    isNew: false,
    startPrice: '0',
  },
];

export const transferTarifOptions = [
  {
    id: 1,
    name: 'Комфорт класс',
    description: '',
    carImg: comfortCar,
    startPrice: 'От 1000р',
    order: 1,
    invisible: false,
  },
  {
    id: 2,
    name: 'Бизнес класс',
    description: '',
    carImg: bisnesCar,
    startPrice: 'От 1000р',
    order: 2,
    invisible: false,
  },
  {
    id: 3,
    name: 'Минивен',
    description: 'до 7 пассажиров',
    carImg: minivenCar,
    startPrice: 'От 1000р',
    order: 3,
    invisible: false,
  },
  {
    id: 4,
    name: 'Микроавтобус',
    description: 'до 20 пассажиров',
    carImg: busCar,
    startPrice: 'От 1000р',
    order: 4,
    invisible: false,
  },
  {
    id: 5,
    name: 'V - Класс',
    description: '',
    carImg: vClassCar,
    startPrice: 'От 1000р',
    order: 5,
    invisible: false,
  },
];

export const reviewsCardsInfo = [
  {
    id: 0,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 4,
  },
  {
    id: 1,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
  {
    id: 2,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
  {
    id: 3,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
  {
    id: 4,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
  {
    id: 5,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
  {
    id: 6,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
  {
    id: 7,
    name: 'Вася Пупкин',
    title: 'круто',
    description: 'Все очень понравилось',
    timeTag: '5 дней назад',
    stars: 5,
  },
];

export const tgImages = [
  watherFallsImg1,
  watherFallsImg2,
  watherFallsImg3,
  blueLaceImg,
  divingImg,
  gaagrImg,
];
